# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  default_locale: '%locale%'
  translator:
    fallbacks: [ '%locale%' ]
  validation: { enable_annotations: true }
  trusted_hosts: ~
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    enabled: true
    handler_id: 'session.handler.native_file'
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
  esi: true
  fragments: true
  php_errors:
    log: true
  serializer:
    enabled: true
    enable_annotations: true
  cache:
    prefix_seed: '%env(PROJECT_SYSTEM_NAME)%'
  http_cache: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: 'session.storage.factory.mock_file'

when@prod:
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: 'cache.adapter.memcached'
        #        adapter: cache.app
        doctrine.system_cache_pool:
          adapter: 'cache.adapter.memcached'
        #        adapter: cache.system
        doctrine_cache_adapter:
          adapter: 'cache.adapter.memcached'
  #        adapter: 'cache.adapter.array'

when@dev:
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
#          adapter: 'cache.adapter.memcached'
          adapter: 'cache.app'
        doctrine.system_cache_pool:
#          adapter: 'cache.adapter.memcached'
          adapter: 'cache.system'
        doctrine_cache_adapter:
#          adapter: 'cache.adapter.memcached'
          adapter: 'cache.adapter.array'
